
package DivisiondelTrabajo;

/**** @author Grupo 1*/
public class Division {
    /*
    
   GRUPO 1:
    
    - MODELO: Guillermo Abraham Marroquin Marroquin     No. Carne: 0900-16-6266
    Funciones:
    * DEFINICION DE ESTRUCTURA DE DATOS PARA LA SELECCION DE LAS PREGUNTAS(REALIZACION DE LAS PREGUNTAS,
    DIAGRAMA DE ESTRUCTURA DE DATOS POR ID, PREGUNTA, RESPUESTA Y RESPRESENTACION DE LA ESTRUCTURAS DE DATOS ID, PREGUNTA, RESPUESTA)
    * CORRECCION Y EL AJUSTE DE LA ESTRUCTURA DE DATOS
    
    - CONTROLADOR: Mario Roberto Vargas Solares         No. Carne. 0900-16-4037
    Funciones:
    * CREACION DE LA PROGRAMACION DE LAS ESTRUCTURAS DE LOS DATOS INICIALES Y FUNCIONES DE CHATBOT
    * CORRECCION Y ERRORES DE RESPUESTAS
    
    - VISTA: Sergio Fernando Sican Patzan               No. Carne. 0900-16-00602
    * PRUEBAS DE RESPUESTAS
    * CREACION DE INTERFAZ GRAFICA
    * ELABORAR LA DOCUMENTACION.
    * */
}
